---
- name: Set a fact about the Ansible python interpreter
  set_fact:
    old_ansible_python_interpreter: "{{ ansible_python_interpreter | default('/usr/bin/python' + ansible_python.version.major | string) }}"

- import_tasks: projects.yml
  vars:
    ansible_python_interpreter: "{{ os_projects_venv ~ '/bin/python' if os_projects_venv != None else old_ansible_python_interpreter }}"
  environment: "{{ os_projects_environment }}"

- name: Ensure openrc environment file exists
  template:
    src: openrc.j2
    dest: "{{ item.1.openrc_file }}"
    mode: 0600
  with_subelements:
    - "{{ os_projects }}"
    - users
    - skip_missing: True
  when: item.1.openrc_file is defined
  loop_control:
    label:
      project: "{{ item.0.name }}"
      user: "{{ item.1.name }}"
  delegate_to: localhost
